"""sprint1_organizations_crud

Revision ID: 91777d506ae8
Revises: 35b6d638fb50
Create Date: 2026-06-15 03:17:51.536888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91777d506ae8'
down_revision: Union[str, None] = '35b6d638fb50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
